name: test

on:
  push:
    branches:
      - "main"

env:
  APP_NAME: fs-go-moby
  POSTGRES_IMAGE: postgres:14.6-alpine

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Go Test
        run: go test ./...
